site_name: IT用語読み方まとめ
docs_dir: 'docs'


theme:
  name: material
  language: ja
  icon:
    logo: material/book-open-variant
    repo: fontawesome/brands/git-alt
  features:
    - tabs

nav:
    - IT用語読み方まとめ: index.md
    - クラウドプラットフォーム:
      - AWS: cloud/aws.md
      - GCP: cloud/gcp.md
      - その他: cloud/other.md
    - 開発環境:
      - ブラウザ: development/browser.md
      - CI/CD: development/ci_cd.md
      - モバイル: development/mobile_app.md
      - プログラミング言語: development/programming_language.md
      - 負荷テスト: development/stress_test.md
      - テストツール: development/testing.md
      - テキストエディタ/IDE: development/text_editor.md
      - 開発ツール: development/tool.md
    - インフラ:
      - 構成管理: infra/configuration_management.md
      - コンテナ: infra/container.md
      - データベース: infra/database.md
      - 分散処理: infra/distributed.md
      - Linuxコマンド: infra/linux_command.md
      - 運用監視: infra/operation.md
      - OS: infra/os.md
      - サーバー: infra/server.md
    - ライブラリ:
      - C#: library/csharp.md
      - CSS: library/css.md
      - JavaScript: library/javascript.md
      - Php: library/php.md
      - Python: library/python.md
    - SaaS:
      - ノーコード: saas/no_code.md
      - SNS: saas/sns.md
      - Web会議: saas/web_meeting.md
      - その他: saas/other.md

markdown_extensions:
    - admonition
    - codehilite:
        linenums: true
        guess_lang: false
        use_pygments: false
        noclasses: true
    - toc:
        permalink: true
