site_name: IT用語読み方まとめ
docs_dir: 'docs'


theme:
  name: material
  language: ja
  icon:
    logo: material/book-open-variant
    repo: fontawesome/brands/git-alt
  features:
    - tabs

nav:
    - IT用語読み方まとめ: index.md
    - クラウドプラットフォーム:
      - AWS: cloud/aws.md
    - 開発環境:
      - モバイル: development/mobile_app.md
      - プログラミング言語: development/programming_language.md
      - テストツール: development/testing.md
      - テキストエディタ/IDE: development/text_editor.md
    - インフラ:
      - OS: infra/os.md
      - 構成管理: infra/configuration_management.md
      - コンテナ: infra/container.md
      - データベース: infra/database.md
      - サーバー: infra/server.md
    - ライブラリ:
      - CSS: library/css.md
      - JavaScript: library/javascript.md
      - Php: library/php.md
      - Python: library/python.md
    - SaaS: saas.md

markdown_extensions:
    - admonition
    - codehilite:
        linenums: true
        guess_lang: false
        use_pygments: false
        noclasses: true
    - toc:
        permalink: true
